version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Argentina/Buenos_Aires
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: production
        patterns:
          - "*"
      development-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: America/Argentina/Buenos_Aires
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
